function run_master
% run_master
%
% Script which sets up parameters and then calls master. Please
% make a local copy of this script.
%
% THIS MASTER RUNS FROM THE PARAM GENERATED BY read_param_xls.m,
% which reads in an excel spread sheet
% (e.g. RADAR_param_YYYY_Mission_Aircraft.xls).
%
% Authors: Brady Maasen, John Paden
%
% See also: master, read_param_xls

%error('Copy this script locally, comment this line, and then run.\n');

% =====================================================================
% User Settings
% =====================================================================
%clear; % Optional
%close all; % Optional

% params = read_param_xls(ct_filename_param('snow_param_2014_Greenland_P3'));
params = read_param_xls(ct_filename_param('rds_param_1998_Greenland_P3'));

clear('param_override');
param_override = [];
param_override.sched.type = 'no scheduler';
param_override.sched.cluster_size = inf;
param_override.sched.rerun_only = false; 
%param_override.sched.submit_arguments    = '-q cresis -l nodes=1:ppn=2:dc2,walltime=60:00';
param_override.sched.stop_on_fail = false;

master(params,param_override);

return;