function [total_num,nc_num,supplement_num,SP_num,map_num,img_num,csv_num] = check_nsidc_files(param, param_override)
% [total_num,nc_num,supplement_num,SP_num,map_num,img_num] = check_nsidc_files(param, param_override)
%
% This function count and check the numbers of nsidc files generated by run_nsidc_delivery_script.m
% param = struct with processing parameters
% param_override = parameters in this struct will override parameters
%         in param.  This struct must also contain the gRadar fields.
%         Typically global gRadar; param_override = gRadar;
%
% Example:
% See run_check_nsidc_files.m for how to run this function directly.
% Authors: Jilu Li

param = merge_structs(param, param_override);

if ~isfield(param,'nsidc_file_type') || isempty(param.nsidc_file_type)
  param.nsidc_file_type = 'L1B';
end

fprintf('=====================================================================\n');
fprintf('%s: %s (%s)\n', mfilename, param.day_seg, datestr(now));
fprintf('=====================================================================\n');

frames = frames_load(param);
bad_frame_idxs = find(frames.proc_mode == 20);
echo_file_num = length(frames.frame_idxs);
if ~isempty(bad_frame_idxs)
  echo_file_num = length(frames.frame_idxs) - length(bad_frame_idxs);
end
if strcmpi(param.nsidc_file_type,'L1B')
  nsidc_SP_file_num_expected = 2*echo_file_num; % each frame has one premet and one spatial file
  map_num = echo_file_num;
  csv_num = 0;
elseif strcmpi(param.nsidc_file_type,'L2')
  map_num = 0;
  csv_num = 1; % each segment has one csv file
  nsidc_SP_file_num_expected = 2*csv_num; 
end
SP_num = nsidc_SP_file_num_expected;
nc_num = 0;
supplement_num = 0;
img_num = 0;
if strcmpi(param.radar_name,'snow8') % 2-18 GHz, with uwb,snow and kuband data products
  nsidc_sensor_str = 'IRSNO1B';
  if regexpi(param.cmd.notes, '2-8 GHz') % 2-8 GHz settings
    nc_num = 2*echo_file_num; % snow qlook and deconv only
    img_num = echo_file_num; % one image (snow decon)
    nsidc_file_num_expected = map_num + nc_num + img_num; 
    if regexpi(param.cmd.mission_names,'sea ice')
      supplement_num = echo_file_num; % one supplement file
      nsidc_file_num_expected = nsidc_file_num_expected + supplement_num;
    end
  else
    nc_num = 4*echo_file_num; % uwb qlook and deconv, snow deconv and kuband deconv
    img_num = 3*echo_file_num; % three echogram images (snow, uwb and kuband, all decon)
    nsidc_file_num_expected = map_num + nc_num + img_num; 
    if regexpi(param.cmd.mission_names,'sea ice')
      supplement_num = 3*echo_file_num; % three supplement files (snow,uwb and kuband)
      nsidc_file_num_expected = nsidc_file_num_expected + supplement_num; 
    end
  end
elseif strcmpi(param.radar_name,'mcords3')
  if strcmpi(param.nsidc_file_type,'L1B')
    nsidc_sensor_str = 'IRMCR1B';
    nc_num = echo_file_num;    % standard or mvdr
    img_num = 2*echo_file_num; % two images with/without picks
    nsidc_file_num_expected = map_num + nc_num + img_num;
  elseif strcmpi(param.nsidc_file_type,'L2')
    nsidc_sensor_str = 'IRMCR2';
    nsidc_file_num_expected = csv_num;
  end
else % other systems to be added
end
total_num = nsidc_file_num_expected;

%% Check nsidc files
% =========================================================================
nsidc_fns = get_filenames(param.nsidc_file_folder,nsidc_sensor_str,param.day_seg,'');
if length(nsidc_fns) == nsidc_file_num_expected
  display('all files found')
elseif length(nsidc_fns) > nsidc_file_num_expected
  display('got extra files!!!!!!')
else
  display('missing files!!!!!!')
end
nsidc_SP_fns = get_filenames(param.nsidc_SP_file_folder,nsidc_sensor_str,param.day_seg,'');
if length(nsidc_SP_fns) == nsidc_SP_file_num_expected
  display('all spatial and premet files found')
elseif length(nsidc_SP_fns) > nsidc_SP_file_num_expected
  display('got extra spatial and premet files!!!!!!')
else
  display('missing spatial and premet files!!!!!!')
end
  




