function [total_num,nc_num,supplement_num,SP_num,map_num,img_num] = check_nsidc_files(param, param_override)
% [total_num,nc_num,supplement_num,SP_num,map_num,img_num] = check_nsidc_files(param, param_override)
%
% This function count and check the numbers of nsidc files generated by run_nsidc_delivery_script.m
% param = struct with processing parameters
% param_override = parameters in this struct will override parameters
%         in param.  This struct must also contain the gRadar fields.
%         Typically global gRadar; param_override = gRadar;
%
% Example:
% See run_check_nsidc_files.m for how to run this function directly.
% Authors: Jilu Li

param = merge_structs(param, param_override);

fprintf('=====================================================================\n');
fprintf('%s: %s (%s)\n', mfilename, param.day_seg, datestr(now));
fprintf('=====================================================================\n');

frames = frames_load(param);
bad_frame_idxs = find(frames.proc_mode == 20);
echo_file_num = length(frames.frame_idxs);
if ~isempty(bad_frame_idxs)
  echo_file_num = length(frames.frame_idxs) - length(bad_frame_idxs);
end
nsidc_SP_file_num_expected = 2*echo_file_num;
SP_num = nsidc_SP_file_num_expected;
map_num = echo_file_num;
supplement_num = 0;
if param.radar_name == 'snow8' % 2-18 GHz, with uwb,snow and kuband data products
  if regexpi(param.cmd.notes, '2-8 GHz') % 2-8 GHz settings
    nc_num = 2*echo_file_num; % snow qlook and deconv only
    img_num = echo_file_num; % one image (snow decon)
    nsidc_file_num_expected = map_num + nc_num + img_num; 
    if regexpi(param.cmd.mission_names,'sea ice')
      supplement_num = echo_file_num; % one supplement file
      nsidc_file_num_expected = nsidc_file_num_expected + supplement_num;
    end
  else
    nc_num = 4*echo_file_num; % uwb qlook and deconv, snow deconv and kuband deconv
    img_num = 3*echo_file_num; % three echogram images (snow, uwb and kuband, all decon)
    nsidc_file_num_expected = map_num + nc_num + img_num; 
    if regexpi(param.cmd.mission_names,'sea ice')
      supplement_num = 3*echo_file_num; % three supplement files (snow,uwb and kuband)
      nsidc_file_num_expected = nsidc_file_num_expected + supplement_num; 
    end
  end
else % other systems to be added
end
total_num = nsidc_file_num_expected;

%% Check nsidc files
% =========================================================================
nsidc_fns = get_filenames(param.nsidc_file_folder,'IRSNO1B',param.day_seg,'');
if length(nsidc_fns) == nsidc_file_num_expected
  display('all files found')
elseif length(nsidc_fns) > nsidc_file_num_expected
  display('got extra files!!!!!!')
else
  display('missing files!!!!!!')
end
nsidc_SP_fns = get_filenames(param.nsidc_SP_file_folder,'IRSNO1B',param.day_seg,'');
if length(nsidc_SP_fns) == nsidc_SP_file_num_expected
  display('all spatial and premet files found')
elseif length(nsidc_SP_fns) > nsidc_SP_file_num_expected
  display('got extra spatial and premet files!!!!!!')
else
  display('missing spatial and premet files!!!!!!')
end
  




