%% Print records headers
fprintf('\nRecords WorkSheet\n');
fprintf('======Copy lines below and paste in records sheet===========\n\n')
fprintf('%s\t1\t%s\t%s\t%s\t%s\n',...
    'Date','file.adcs','geotiff_fn',...
    'frame_mode','file_version')
fprintf('%s\t%s\t%s\t%s\t%s\t%s\n',...
    'YYYYMMDD','Segment','r','t','r','r')