%% Print vectors headers
fprintf('\nVectors WorkSheet\n');
fprintf('======Copy lines below and paste in vectors sheet===========\n\n')
fprintf('%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n', ...
    'Date', '1','file.adc', 'file.start_idx', 'file.stop_idx',...
    'file.base_dir', 'file.adc_folder_name', 'file.file_prefix',...
    'gps.time_offset');

fprintf('%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n', ...
'YYYYMMDD','Segment','r','r','r','t','t','t','r');